___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [7]:
pd.Series(data = arr, index = labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [8]:
d

{'a': 10, 'b': 20, 'c': 30}

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(data = d, index= ['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [11]:
pd.Series(data = "Steve")

0    Steve
dtype: object

In [12]:
pd.Series(data = "Steve", index = range(10,13))

10    Steve
11    Steve
12    Steve
dtype: object

In [13]:
pd.Series(data = 10, index= ['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [14]:
set1 = (1,2,3,6)

In [15]:
pd.Series(set1)

0    1
1    2
2    3
3    6
dtype: int64

In [16]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [17]:
pd.Series(set)[0]([2,5,7,5,8,2])

{2, 5, 7, 8}

In [18]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [19]:
pd.Series([sum, print, len])[1]("a")

a


In [20]:
pd.Series([sum, print, len])[2]("clarusway")

9

In [21]:
mix_data = ['Aziz', 2, True]

In [22]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [23]:
ser.dtype

dtype('O')

In [24]:
type(ser)

pandas.core.series.Series

In [25]:
type(ser[1])

int

In [26]:
type(ser[0])

str

In [27]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [28]:
type(arr[2])

numpy.str_

### Basic Attributes of Series

In [29]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    76
1    50
2    51
3    37
4    48
5    36
6    29
dtype: int32

In [30]:
type(ser)

pandas.core.series.Series

In [31]:
ser.dtype

dtype('int32')

In [32]:
ser.shape

(7,)

In [33]:
ser.size

7

In [34]:
len(ser)

7

In [35]:
ser.ndim

1

In [36]:
ser

0    76
1    50
2    51
3    37
4    48
5    36
6    29
dtype: int32

In [37]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [38]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [39]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [40]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [41]:
ser.values

array([76, 50, 51, 37, 48, 36, 29])

In [42]:
[i for i in ser.values]

[76, 50, 51, 37, 48, 36, 29]

In [43]:
ser.items()

In [44]:
list(ser.items())

[(0, 76), (1, 50), (2, 51), (3, 37), (4, 48), (5, 36), (6, 29)]

In [45]:
for index, value in ser.items():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : 76
Index : 1, Value : 50
Index : 2, Value : 51
Index : 3, Value : 37
Index : 4, Value : 48
Index : 5, Value : 36
Index : 6, Value : 29


In [46]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])

In [47]:
ser

c     9
b     8
a    24
e     6
f    10
d    10
g    18
i    24
h     6
j    17
dtype: int32

In [48]:
ser.head(3)

c     9
b     8
a    24
dtype: int32

In [49]:
ser.tail(2)

h     6
j    17
dtype: int32

In [50]:
ser.sample(2)

a    24
b     8
dtype: int32

In [51]:
ser.sort_index(ascending = True)

a    24
b     8
c     9
d    10
e     6
f    10
g    18
h     6
i    24
j    17
dtype: int32

In [52]:
ser.sort_values(ascending = False)

a    24
i    24
g    18
j    17
f    10
d    10
c     9
b     8
e     6
h     6
dtype: int32

In [53]:
ser

c     9
b     8
a    24
e     6
f    10
d    10
g    18
i    24
h     6
j    17
dtype: int32

In [54]:
ser.isin([5, 9])

c     True
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [55]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [56]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [57]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                      

In [58]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [59]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [60]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [61]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [62]:
ser1[1]

2

In [63]:
ser1['Germany']

2

In [64]:
ser2['Japan']

4

In [65]:
ser1.Germany

2

Operations are then also done based off of index:

In [66]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [67]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])

ser3

0    a
1    b
2    c
3    d
dtype: object

In [68]:
ser3[0]

'a'

In [69]:
ser3[2:]

2    c
3    d
dtype: object

In [70]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [71]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [72]:
panser['terry']

121

In [73]:
panser[0]

121

In [74]:
index1 = ['terry', 'micheal', 'jason']

In [75]:
panser[index1]

terry      121
micheal    200
jason       99
dtype: int64

In [76]:
panser['terry':'orion']

terry      121
micheal    200
orion      150
dtype: int64

In [77]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes and Some New Attributes

In [78]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [79]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [80]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [81]:
panser.items()

In [82]:
list(panser.items())

[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [83]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [84]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [85]:
'terry' in panser

True

In [86]:
'bob' in panser

False

In [87]:
121 in panser.values

True

In [88]:
55 in panser.values

False

In [89]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [90]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [91]:
panser['terry'] = 90

In [92]:
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [93]:
panser[panser < 100]

terry    90
jason    99
dtype: int64

In [94]:
panser[panser < 100] = 100
panser

terry      100
micheal    200
orion      150
jason      100
dtype: int64

In [95]:
panser[panser > 100]

micheal    200
orion      150
dtype: int64